### PR TITLE
Flip dropdown icon when folder is expanded

### PR DESCRIPTION
**Pull request by mattfelsen**
Bored on ✈️ 👍🏼 Adds a feature request by @transat in #68

### CODE REVIEW

**Comment by transat** [comment]
Great. Much better. Cheers.

**Comment by transat** [comment]
The only issue of course is that when using a custom dropdown icon, it needs to make sense when flipped. @mattfelsen, any chance this could be tweaked to check for the existence of an optional 'close' icon? If such an icon exists in the theme (and bin/data/ofxbraitsch/ofxdatgui folder) then it could get used instead of the flip?

**Comment by braitsch** [comment]
Thanks @mattfelsen! After thinking about this a bit I'd prefer to have separate icons that reflect a group's open vs closed state rather than manipulate one icon programatically. This is how toggle/radio buttons currently work (icon-radio-on.png & icon-radio-off.png). Separate icons will allow the most control over the visual state and the overhead of an additional icon file will be negligible.

**Comment by mattfelsen** [comment]
Yep, agreed 👍🏼

**Pull request closed without merging**
